# Generated by Django 4.0.2 on 2022-03-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionType', models.IntegerField()),
                ('params', models.JSONField()),
                ('description', models.TextField()),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.action')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.scenario')),
            ],
        ),
    ]
