# Generated by Django 4.0.2 on 2022-03-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_action_description_alter_action_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.action'),
        ),
    ]
