# Generated by Django 4.0.2 on 2022-03-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_action_description_alter_action_params_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('data', models.JSONField(blank=True, null=True)),
                ('screen', models.ImageField(null=True, upload_to='')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.scenario')),
            ],
        ),
    ]
